src/Entity/CommandeProduit.php
<?php

namespace App\Entity;

use App\Repository\CommandeProduitRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommandeProduitRepository::class)
 */
class CommandeProduit
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite;

    /**
     * @ORM\ManyToOne(targetEntity=Produit::class, inversedBy="commandeProduits", cascade={"remove"})
     * @ORM\JoinColumn(nullable=true, name="produit", referencedColumnName="reference_p")
     */
    private $produit;

    /**
     * @ORM\ManyToOne(targetEntity=Commande::class, inversedBy="commandeProduits", cascade={"remove"})
     * @ORM\JoinColumn(nullable=true, name="commande", referencedColumnName="id")
     */
    private $commande;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): self
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getProduit(): ?Produit
    {
        return $this->produit;
    }

    public function setProduit(?Produit $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getCommande(): ?Commande
    {
        return $this->commande;
    }

    public function setCommande(?Commande $commande): self
    {
        $this->commande = $commande;

        return $this;
    }
    public function __toString()
    {
        return (string)$this->getId();

    }
}

src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Reference_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Nom_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Type_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")

     */
    private $Marque_P;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Prix_P;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Quantite_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Image_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Description_P;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Quantite_V;


    /**
     * @ORM\ManyToOne(targetEntity=CategorieP::class, inversedBy="produits"  )
     * @ORM\JoinColumn(nullable=false,name="Categorie", referencedColumnName="reference_c")
     */
    private $Categorie;

    /**
     * @ORM\OneToMany(targetEntity=CommandeProduit::class, mappedBy="produit",cascade={"persist"}, cascade={"remove"})
     */
    private $commandeProduits;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur;

    public function __construct()
    {
        $this->commandeProduits = new ArrayCollection();
    }

   // /**
     //* @ORM\ManyToMany(targetEntity=Commande::class, inversedBy="produits")
     //* @ORM\JoinTable(name="commandes_produits",
     //*     joinColumns={@ORM\JoinColumn(name="produit_ref", referencedColumnName="reference_p")},
     //*     inverseJoinColumns={@ORM\JoinColumn(name="id_commande",referencedColumnName="id")}
     //*    )
     //*/
    //private $commandes;

   /* public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }*/




    public function getReferenceP(): ?string
    {
        return $this->Reference_P;
    }

    public function setReferenceP(string $Reference_P): self
    {
        $this->Reference_P = $Reference_P;

        return $this;
    }

    public function getNomP(): ?string
    {
        return $this->Nom_P;
    }

    public function setNomP(string $Nom_P): self
    {
        $this->Nom_P = $Nom_P;

        return $this;
    }

    public function getTypeP(): ?string
    {
        return $this->Type_P;
    }

    public function setTypeP(string $Type_P): self
    {
        $this->Type_P = $Type_P;

        return $this;
    }

    public function getMarqueP(): ?string
    {
        return $this->Marque_P;
    }

    public function setMarqueP(string $Marque_P): self
    {
        $this->Marque_P = $Marque_P;

        return $this;
    }

    public function getPrixP(): ?float
    {
        return $this->Prix_P;
    }

    public function setPrixP(float $Prix_P): self
    {
        $this->Prix_P = $Prix_P;

        return $this;
    }

    public function getQuantiteP(): ?int
    {
        return $this->Quantite_P;
    }

    public function setQuantiteP(?int $Quantite_P): self
    {
        $this->Quantite_P = $Quantite_P;

        return $this;
    }

    public function getImageP()
    {
        return $this->Image_P;
    }

    public function setImageP( $Image_P)
    {
        $this->Image_P = $Image_P;

        return $this;
    }

    public function getDescriptionP(): ?string
    {
        return $this->Description_P;
    }

    public function setDescriptionP(string $Description_P): self
    {
        $this->Description_P = $Description_P;

        return $this;
    }

    public function getCategorieP(): ?CategorieP
    {
        return $this->CategorieP;
    }

    public function setCategorieP(?CategorieP $CategorieP): self
    {
        $this->CategorieP = $CategorieP;

        return $this;
    }

    public function getCategorie(): ?CategorieP
    {
        return $this->Categorie;
    }

    public function setCategorie(?CategorieP $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }


    public function __toString()
    {
        return (string)$this->getNomP();

    }

    public function getQuantiteV(): ?int
    {
        return $this->Quantite_V;
    }

    public function setQuantiteV(?int $Quantite_V): self
    {
        $this->Quantite_V+= $Quantite_V;

        return $this;
    }

 //   /**
   //  * @return Collection|Commande[]
     //*/
    /*public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
          //  $commande->addProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        $this->commandes->removeElement($commande);

        return $this;
    }*/
    public function nvquantite(?int $nv): self{
        $this->Quantite_P-=$nv;
        return $this;

    }
    public function vente(){
       $vente=$this->getQuantiteV();
       $stock=$this->getQuantiteP();
       $pourcentage=($vente*100)/$stock;
       return $pourcentage;

    }

    /**
     * @return Collection|CommandeProduit[]
     */
    public function getCommandeProduits(): Collection
    {
        return $this->commandeProduits;
    }

    public function addCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if (!$this->commandeProduits->contains($commandeProduit)) {
            $this->commandeProduits[] = $commandeProduit;
            $commandeProduit->setProduit($this);
        }

        return $this;
    }

    public function removeCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if ($this->commandeProduits->removeElement($commandeProduit)) {
            // set the owning side to null (unless already changed)
            if ($commandeProduit->getProduit() === $this) {
                $commandeProduit->setProduit(null);
            }
        }

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }
    }

src/Controller/CommandeProduitController.php
<?php

namespace App\Controller;

use App\Entity\Commande;
use App\Entity\CommandeProduit;
use App\Repository\CommandeProduitRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Repository\CommandeRepository;
use App\Repository\ProduitRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;

class CommandeProduitController extends AbstractController
{
    // /**
    //  * @Route("/commande/produit", name="commande_produit")
    //*/
    /* public function index(): Response
     {
         return $this->render('commande_produit/index.html.twig', [
             'controller_name' => 'CommandeProduitController',
         ]);
     }*/
    /**
     * @Route("/ajouter/commande",name="addCommande")
     */
    public function ajouterCommande(SessionInterface $session, ProduitRepository $repository)
    {
        $panier = $session->get('panier');
       // $em = $this->getDoctrine()->getManager();
       /* $commandeproduit = new CommandeProduit();
        $commande = new Commande();*/
        $priTot = 0;
        $produits = [];
        foreach ($panier as $id => $quantity) {

            $produit = $repository->find($id);
            /*$produit->setQuantiteV($quantity);
            $produit->nvquantite($quantity);*/
            //$commandeproduit->setQuantite($quantity);
            //$em->flush();
            $priTot += $quantity * $produit->getPrixP();
            //$produit->addCommandeProduit($commandeproduit);
            //$commande->addCommandeProduit($commandeproduit);
            $produits[] = $produit;
        }
       /* $commande->setDate(new\ dateTime());
        $commande->setPrixtotal($priTot);


        // $user = $this->getUser();
        $commande->setUser($this->getUser());//emna
        $em->persist($commande);
        $em->persist($commandeproduit);
        $session->set('panier', []);
        $em->flush();*/
        return $this->render('commande_produit/tojrabjust.html.twig', ['produits' => $produits]);
// return $this->render('commande_produit/index.html.twig');

    }


    /**
     * @param CommandeRepository $repository
     * * @param CommandeProduitRepository $rep
     * @return Response
     * @Route ("/commande/affiche",name="affiche_commande")
     */
    public function affichecommandeproduit(CommandeRepository $repository,CommandeProduitRepository $rep,SessionInterface $session)
    {
        return $this->render('commande_produit/index.html.twig', ['commande' => $repository->findAll(),
        'commandeproduit'=>$rep->findAll()]);


    }

}

templates/commande_produit/index.html.twig
{% extends 'front_base.html.twig' %}
{% block title %}produit{% endblock %}
{% block head %}
<head>
    <title>Single Product</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Colo Shop Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/styles/bootstrap4/bootstrap.min.css') }}">
    <link href="{{ asset('front/plugins/font-awesome-4.7.0/css/font-awesome.min.css') }}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/plugins/OwlCarousel2-2.2.1/owl.carousel.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/plugins/OwlCarousel2-2.2.1/owl.theme.default.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/plugins/OwlCarousel2-2.2.1/animate.css') }}">
    <link rel="stylesheet" href="{{ asset('front/plugins/themify-icons/themify-icons.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/plugins/jquery-ui-1.12.1.custom/jquery-ui.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/styles/single_styles.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('front/styles/single_responsive.css') }}">
    <style>
        .fontCommande{
            font-family: "Roboto",sans-serif;
            font-size: 15px;
            font-weight: 400;
            line-height: 1.667;

        }
        table {

            display: table;
            border-collapse: separate;
            box-sizing: border-box;
            text-indent: initial;
            border-spacing: 2px;
            border-color: grey;
        }
        .order_details_table .table {
            margin-bottom: 0px;
        }
        .order_details_table {
            margin-bottom: 45px;
            margin-left: 350px;
            margin-right: 350px;
            background: #e5ecee;
            padding: 30px;
            margin-top: 75px;
        }

        .table-responsive {
            display: block;
            width: 100%;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
            -ms-overflow-style: -ms-autohiding-scrollbar;
        }
    </style>
</head>
{% endblock %}

{% block body %}
<body>

<div class="container">



    <div class="order_details_table">
        <h2 align="center" style="margin-top: 20px;font-style: italic;"> details de votre ordre</h2>
        <div class="table-responsive">
            <table class="table">

                <thead>

                <tr>
                    <th scope="col">produit</th>
                    <th scope="col"> quantite  </th>
                    <th scope="col"> total  </th>
                </tr>
                </thead>


                <tbody>
                {% set tot =0 %}
                {% for c in commande %}
                    {% for p in c.commandeproduits %}
                        <tr>
                            <th scope="col" class="fontCommande">{{ p.produit.NomP }}

                            </th>
                            <th scope="col" class="fontCommande"> {{ p.quantite }}  </th>
                            <th scope="col" class="fontCommande"> {{ p.produit.PrixP * p.quantite }}  </th>
                            {% set tot =tot + (p.produit.PrixP * p.quantite)%}
                        </tr>
                    {% endfor %}

                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td><a href="javascript:history.go(-2)" class="btn btn-warning text-white"><i class="fa fa-angle-left"></i> Continuer votre Shopping</a></td>
                    <td colspan="2" class="hidden-xs"></td>
                    <td class="hidden-xs text-center" style="width:10%;"><strong>Total : {{ tot }}</strong></td>
                    <td><a href="" class="btn btn-success btn-block">livraison gratuite <i class="fa fa-angle-right"></i></a></td>
                </tr>
                </tfoot>



            </table>


        </div>


    </div>



    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="footer_nav_container d-flex flex-sm-row flex-column align-items-center justify-content-lg-start justify-content-center text-center">
                        <ul class="footer_nav">
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">FAQs</a></li>
                            <li><a href="contact.html">Contact us</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="footer_social d-flex flex-row align-items-center justify-content-lg-end justify-content-center">
                        <ul>
                            <li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
                            <li><a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer_nav_container">
                        <div class="cr">©2018 All Rights Reserverd. This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="#">Colorlib</a></div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

</div>

<script src="{{ asset('front/js/jquery-3.2.1.min.js') }}"></script>
<script src="{{ asset('front/styles/bootstrap4/popper.js') }}"></script>
<script src="{{ asset('front/styles/bootstrap4/bootstrap.min.js') }}"></script>
<script src="{{ asset('front/plugins/Isotope/isotope.pkgd.min.js') }}"></script>
<script src="{{asset ('front/plugins/easing/easing.js') }}"></script>
<script src="{{ asset('front/plugins/jquery-ui-1.12.1.custom/jquery-ui.js') }}"></script>

</body>
{% endblock %}

templates/commande_produit/tojrabjust.html.twig
{% extends 'front_base.html.twig' %}
{% block title %}produit{% endblock %}
{% block styleMap %}
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
          integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
          crossorigin=""/>
{%  endblock %}
{% block body %}
    <style>

        @import url(https://fonts.googleapis.com/css?family=Lato:400,300,700);
        body,html {
            height:100%;
            margin:0;
            font-family:lato;
        }

        h2 {
            margin-bottom:0px;
            margin-top:25px;
            text-align:center;
            font-weight:200;
            font-size:19px;
            font-size:1.2rem;

        }

        .dropdown-select.visible {
            display:block;
        }
        .dropdown {
            position:relative;
        }
        ul {
            margin:0;
            padding:0;
        }
        ul li {
            list-style:none;
            padding-left:10px;
            cursor:pointer;
        }
        ul li:hover {
            background:rgba(255,255,255,0.1);
        }
        .dropdown-select {
            position:absolute;
            background:#77aaee;
            text-align:left;
            box-shadow:0px 3px 5px 0px rgba(0,0,0,0.1);
            border-bottom-right-radius:5px;
            border-bottom-left-radius:5px;
            width:90%;
            left:2px;
            line-height:2em;
            margin-top:2px;
            box-sizing:border-box;
        }
        .thin {
            font-weight:400;
        }
        .small {
            font-size:12px;
            font-size:.8rem;
        }
        .half-input-table {
            border-collapse:collapse;
            width:100%;
        }
        .half-input-table td:first-of-type {
            border-right:10px solid #4488dd;
            width:50%;
        }
        .window {

            background:#fff;
            display:-webkit-box;
            display:-webkit-flex;
            display:-ms-flexbox;
            display:flex;
            border-radius:30px;
            z-index:10;
        }
        .order-info {
            height:100%;
            width:50%;
            padding-left:25px;
            padding-right:25px;
            box-sizing:border-box;
            display:-webkit-box;
            display:-webkit-flex;
            display:-ms-flexbox;
            display:flex;
            -webkit-box-pack:center;
            -webkit-justify-content:center;
            -ms-flex-pack:center;
            justify-content:center;
            position:relative;
        }
        .price {
            bottom:0px;
            position:absolute;
            right:0px;
            color:#4488dd;
        }
        .order-table td:first-of-type {
            width:25%;
        }
        .order-table {
            position:relative;
        }
        .line {
            height:1px;
            width:100%;
            margin-top:10px;
            margin-bottom:10px;
            background:#ddd;
        }
        .order-table td:last-of-type {
            vertical-align:top;
            padding-left:25px;
        }
        .order-info-content {
            table-layout:fixed;

        }

        .full-width {
            width:100%;
        }
        .pay-btn {
            border:none;
            background:#22b877;
            line-height:2em;
            border-radius:10px;
            font-size:19px;
            font-size:1.2rem;
            color:#fff;
            cursor:pointer;
            position:absolute;
            bottom:25px;
            width:calc(100% - 50px);
            -webkit-transition:all .2s ease;
            transition:all .2s ease;
        }
        .pay-btn:hover {
            background:#22a877;
            color:#eee;
            -webkit-transition:all .2s ease;
            transition:all .2s ease;
        }

        .total {
            margin-top:25px;
            font-size:20px;
            font-size:1.3rem;
            position:absolute;
            bottom:30px;
            right:27px;
            left:35px;
        }

        #mapid { height: 200px; }

        .dense {
            line-height:1.2em;
            font-size:16px;
            font-size:1rem;
        }
        .input-field {
            background:rgba(255,255,255,0.1);
            margin-bottom:10px;
            margin-top:3px;
            line-height:1.5em;
            font-size:20px;
            font-size:1.3rem;
            border:none;
            padding:5px 10px 5px 10px;
            color:#fff;
            box-sizing:border-box;
            width:100%;
            margin-left:auto;
            margin-right:auto;
        }
        .credit-info {
            background:#fe4c50;
            height:100%;
            width:50%;
            color:#eee;
            -webkit-box-pack:center;
            -webkit-justify-content:center;
            -ms-flex-pack:center;
            justify-content:center;
            font-size:14px;
            font-size:.9rem;
            display:-webkit-box;
            display:-webkit-flex;
            display:-ms-flexbox;
            display:flex;
            box-sizing:border-box;
            padding-left:25px;
            padding-right:25px;
            border-top-right-radius:30px;
            border-bottom-right-radius:30px;
            position:relative;
        }
        .dropdown-btn {
            background:rgba(255,255,255,0.1);
            width:100%;
            border-radius:5px;
            text-align:center;
            line-height:1.5em;
            cursor:pointer;
            position:relative;
            -webkit-transition:background .2s ease;
            transition:background .2s ease;
        }
        .dropdown-btn:after {
            content: '\25BE';
            right:8px;
            position:absolute;
        }
        .dropdown-btn:hover {
            background:rgba(255,255,255,0.2);
            -webkit-transition:background .2s ease;
            transition:background .2s ease;
        }
        .dropdown-select {
            display:none;
        }
        .credit-card-image {
            display:block;
            max-height:80px;
            margin-left:auto;
            margin-right:auto;
            margin-top:35px;
            margin-bottom:15px;
        }
        .credit-info-content {
            margin-top:25px;
            -webkit-flex-flow:column;
            -ms-flex-flow:column;
            flex-flow:column;
            display:-webkit-box;
            display:-webkit-flex;
            display:-ms-flexbox;
            display:flex;
            width:100%;
        }

            .window {
                width: 100%;
                height: 100%;
                display:block;
                border-radius:0px;
            }
            .order-info {
                width:100%;
                height:auto;

                border-radius:0px;
            }
            .credit-info {
                width:100%;
                height:auto;

                border-radius:0px;
            }
            .pay-btn {
                border-radius:0px;
            }



    </style>

<div class='container'>

    <div class='window'>
        <div class='order-info'>
            <div class='order-info-content'>
                <h2>Order Summary</h2>
                <div class='line'></div>
                {% for p in produits  %}
                <table class='order-table'>
                    <tbody>
                    <tr>
                        <td><img src="{{ asset('/back/img/' ~ p.ImageP)}}" width="200" height="200">
                        </td>
                        <td>
                            <br> <span class='thin'>{{ p.nomP }}</span>
                            <br> {{ p.marqueP }}<br> <span class='thin small'> Color: Grey/Orange, Size: 10.5<br><br></span>
                        </td>

                    </tr>
                    <tr>
                        <td>
                            <div class='price'>Dt{{ p.prixP }}</div>
                        </td>
                    </tr>
                    </tbody>

                </table>
                <div class='line'></div>
                {% endfor %}
            </div>
        </div>

        <div class='credit-info'>
            <div class='credit-info-content'>
                Veuiller choisir votre destination
                <form action="{{ path('ajouterLivre') }}" method="get">
                <input class='input-field' id="searchInputDist" name="distination">
               <a href=""  class="btn btn-success btn-block" style="color: #FFFFFF" id="searchDest">chercher </a>
                <input type="submit" value="livrer" class="btn btn-success btn-block">
                </form>





            </div>

        </div>

    </div>

</div>
    <br>
    <div class="container contact_container">
        <div class="row">
            <div class="col">
                <div id="mapid"></div>

            </div>

        </div>
    </div>

{% endblock %}
{% block javascripts %}
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
            integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
            crossorigin=""></script>

    <script>


        let carte = L.map('mapid').setView([36.8194382,9.5613714], 12);


        L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            maxZoom: 18,

            tileSize: 512,
            zoomOffset: -1,

        }).addTo(carte);
        L.popup()
            .setLatLng([35.6715066,10.0905415])
            .setContent('<p>Hello world!<br />This is a nice popup.</p>')
            .openOn(carte);





    </script>
    <script>
        const link = document.querySelector('#searchDest')
        link.addEventListener('click',searchDestination)
        function searchDestination(event){
            event.preventDefault()
            const q =  document.querySelector('#searchInputDist').value;
            if(q ===""){

                alert('you have to right a destination');
            }
            else{

                const    url = 'https://nominatim.openstreetmap.org/?addressdetails=1&q='+q+'%27&format=json&limit=1';

                return load(url)
            }



        }
        async function load(url){

            const response = await fetch(url).catch(function (error){
                if(error.response.status === 403){
                    window.alert("vous avez deja signalez ce commmentaire ")
                }
            });
            const data =await response.json()



            if(data.length === 0){

                alert('veuiller choisir une vile tunisienne')
            }
            else if (data[0].address.country != 'Tunisie'){

                alert('veuiller choisir une vile tunisienne')
            }

            else{
                L.popup()
                    .setLatLng([data[0].lat,data[0].lon])
                    .setContent('<p>Hello world!<br />This is a nice popup.</p>')
                    .openOn(carte);


            }
//           console
            //console.log(data);







            //replie.innerHTML = data.reps
            //playMusic()










        }



    </script>


{% endblock %}



