src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Reference_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Nom_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Type_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")

     */
    private $Marque_P;

    /**
     * @ORM\Column(type="float")
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Prix_P;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Quantite_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Image_P;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Champs obligatoir")
     */
    private $Description_P;
    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Quantite_V;


    /**
     * @ORM\ManyToOne(targetEntity=CategorieP::class, inversedBy="produits"  )
     * @ORM\JoinColumn(nullable=false,name="Categorie", referencedColumnName="reference_c")
     */
    private $Categorie;

    /**
     * @ORM\OneToMany(targetEntity=CommandeProduit::class, mappedBy="produit",cascade={"persist"}, cascade={"remove"})
     */
    private $commandeProduits;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $couleur;

    public function __construct()
    {
        $this->commandeProduits = new ArrayCollection();
    }

   // /**
     //* @ORM\ManyToMany(targetEntity=Commande::class, inversedBy="produits")
     //* @ORM\JoinTable(name="commandes_produits",
     //*     joinColumns={@ORM\JoinColumn(name="produit_ref", referencedColumnName="reference_p")},
     //*     inverseJoinColumns={@ORM\JoinColumn(name="id_commande",referencedColumnName="id")}
     //*    )
     //*/
    //private $commandes;

   /* public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }*/




    public function getReferenceP(): ?string
    {
        return $this->Reference_P;
    }

    public function setReferenceP(string $Reference_P): self
    {
        $this->Reference_P = $Reference_P;

        return $this;
    }

    public function getNomP(): ?string
    {
        return $this->Nom_P;
    }

    public function setNomP(string $Nom_P): self
    {
        $this->Nom_P = $Nom_P;

        return $this;
    }

    public function getTypeP(): ?string
    {
        return $this->Type_P;
    }

    public function setTypeP(string $Type_P): self
    {
        $this->Type_P = $Type_P;

        return $this;
    }

    public function getMarqueP(): ?string
    {
        return $this->Marque_P;
    }

    public function setMarqueP(string $Marque_P): self
    {
        $this->Marque_P = $Marque_P;

        return $this;
    }

    public function getPrixP(): ?float
    {
        return $this->Prix_P;
    }

    public function setPrixP(float $Prix_P): self
    {
        $this->Prix_P = $Prix_P;

        return $this;
    }

    public function getQuantiteP(): ?int
    {
        return $this->Quantite_P;
    }

    public function setQuantiteP(?int $Quantite_P): self
    {
        $this->Quantite_P = $Quantite_P;

        return $this;
    }

    public function getImageP()
    {
        return $this->Image_P;
    }

    public function setImageP( $Image_P)
    {
        $this->Image_P = $Image_P;

        return $this;
    }

    public function getDescriptionP(): ?string
    {
        return $this->Description_P;
    }

    public function setDescriptionP(string $Description_P): self
    {
        $this->Description_P = $Description_P;

        return $this;
    }

    public function getCategorieP(): ?CategorieP
    {
        return $this->CategorieP;
    }

    public function setCategorieP(?CategorieP $CategorieP): self
    {
        $this->CategorieP = $CategorieP;

        return $this;
    }

    public function getCategorie(): ?CategorieP
    {
        return $this->Categorie;
    }

    public function setCategorie(?CategorieP $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }


    public function __toString()
    {
        return (string)$this->getNomP();

    }

    public function getQuantiteV(): ?int
    {
        return $this->Quantite_V;
    }

    public function setQuantiteV(?int $Quantite_V): self
    {
        $this->Quantite_V+= $Quantite_V;

        return $this;
    }

 //   /**
   //  * @return Collection|Commande[]
     //*/
    /*public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes[] = $commande;
          //  $commande->addProduit($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        $this->commandes->removeElement($commande);

        return $this;
    }*/
    public function nvquantite(?int $nv): self{
        $this->Quantite_P-=$nv;
        return $this;

    }
    public function vente(){
       $vente=$this->getQuantiteV();
       $stock=$this->getQuantiteP();
       $pourcentage=($vente*100)/$stock;
       return $pourcentage;

    }

    /**
     * @return Collection|CommandeProduit[]
     */
    public function getCommandeProduits(): Collection
    {
        return $this->commandeProduits;
    }

    public function addCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if (!$this->commandeProduits->contains($commandeProduit)) {
            $this->commandeProduits[] = $commandeProduit;
            $commandeProduit->setProduit($this);
        }

        return $this;
    }

    public function removeCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if ($this->commandeProduits->removeElement($commandeProduit)) {
            // set the owning side to null (unless already changed)
            if ($commandeProduit->getProduit() === $this) {
                $commandeProduit->setProduit(null);
            }
        }

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(?string $couleur): self
    {
        $this->couleur = $couleur;

        return $this;
    }
    }

src/Controller/DermatologueController.php
<?php

namespace App\Controller;

use App\Entity\CategorieDerm;
use App\Entity\Dermatologue;
use App\Entity\User;
use App\Form\DermatologueType;
use App\Form\DermMType;
use App\Repository\DermatologueRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class DermatologueController extends RegistrationController
{
    /**
     * @Route("/dermatologues", name="dermatologues")
     */
    public function list ()
    {

        $dermatologues = $this->getDoctrine()->getRepository(Dermatologue::class)->findAll();


        return $this->render('dermatologue/affichederm.html.twig', [
            'dermatologues' => $dermatologues,
        ]);
    }

   /**
     * @Route("/dermatologuesfront/affiche/{ref}", name="dermfront")
     */
    public function listfront ($ref)
    {

        $dermatologues = $this->getDoctrine()->getRepository(Dermatologue::class)->findAll();
        $categories = $this->getDoctrine()->getRepository(CategorieDerm::class)->findAll();

        return $this->render('dermatologue/afficherdermatologuefront.html.twig', [
            'dermatologues' => $dermatologues,
            'ref'=> $ref,
            'categories'=> $categories
        ]);
    }

    /**
     * @Route("/dermatologuesfront/affiche1/{id}", name="dermfront1")
     */
    public function listfrontderm ($id)
    {

        $dermatologues = $this->getDoctrine()->getRepository(Dermatologue::class)->find($id);


        return $this->render('dermatologue/afficher1dermatologuefront.html.twig', [
            'dermatologues' => $dermatologues,
            'id'=> $id
        ]);
    }




    /**
     * @Route("/Supderm/{id}", name="derm")
     */
    public function Delete($id,DermatologueRepository $repository)
    {
        $dermatologue=$repository->find($id);

        $em=$this->getDoctrine()->getManager();
        $em->remove($dermatologue);
        $em->flush();

        return $this->redirectToRoute('dermatologues');

    }

   /* /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route ("dermatologue/Ajoutderm" ,  name="ajoutderm")
     */
   /* function add(Request $request ,UserPasswordEncoderInterface $passwordEncoder) {


        $dermatologues=new Dermatologue();
        $form=$this->createForm(DermatologueType::class,$dermatologues);
        $form->add('Ajouter', SubmitType::class) ;
        $form->handleRequest($request);
        //$dc2array = unserialize($dermatologues->getAssurancemaladie(), ['allowed_classes' => false]);
        //var_dump($dc2array);

        if($form->isSubmitted()&& $form->isValid())
        {
            $path=$this->getParameter('kernel.project_dir').'/public/back/img';
            $dermatologues=$form->getData();
            $file=$dermatologues->getImage();
            $fileName=md5(uniqid()).'.'.$file->guessExtension();
            try {
                $file->move($path,$fileName);
            }catch(FileException $e){

            }
            $em=$this->getDoctrine()->getManager() ;
            $dermatologues->setImage($fileName);
            $dermatologues->setPassword(
                $passwordEncoder->encodePassword(
                    $dermatologues,
                    $form->get('password')->getData()
                ));
            $em->persist($dermatologues);

            $em->flush();
            return $this->redirectToRoute('dermatologues');
        }
        return $this->render ('dermatologue/Ajoutderm.html.twig',[
            'form'=>$form->createView()
        ]) ;
    }*/

    /**
     * @Route ("dermatologue/Update/{id}" , name="updatederm")
     */
    function Update(DermatologueRepository $repository,$id,Request $request){
        //$repository = $this->getDoctrine()->getRepository(User::class);
        //$user = $repository->find($id);
        $dermatologues=$repository->find($id);
        $form=$this->createForm(DermMType::class,$dermatologues) ;
        $form->add('Modifier',SubmitType::class) ;
        $form->handleRequest($request) ;

        if($form->isSubmitted()&& $form->isValid())
        {
            $em=$this->getDoctrine()->getManager() ;
            $em->flush();
            return $this->redirectToRoute('dermatologues');
        }
        return $this->render('dermatologue/ModifDerm.html.twig',[
            'f'=>$form->createView()
        ]) ;
    }
    /**
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @Route ("dermatologue/Ajoutu/{id}" ,  name="ajoutdermu")
     */
    function addus(Request $request ,$id) {

        $dermatologues=new Dermatologue();

        $repository = $this->getDoctrine()->getRepository(User::class);
        $user = $repository->find($id);


        //$dermatologues->setId($user->getId());
        $dermatologues->setEmail($user->getEmail());
        $dermatologues->setRoles($user->getRoles());
        $dermatologues->setPassword($user->getPassword());
        $dermatologues->setCin($user->getCin());
        $dermatologues->setNom($user->getNom());
        $dermatologues->setPrenom($user->getPrenom());
        $dermatologues->setAdresse($user->getAdresse());
        $dermatologues->setNumero($user->getNumero());
        $em=$this->getDoctrine()->getManager() ;

        $form=$this->createForm(DermatologueType::class,$dermatologues);

        $form->add('Ajouter', SubmitType::class) ;

        $form->handleRequest($request);
        //$dc2array = unserialize($dermatologues->getAssurancemaladie(), ['allowed_classes' => false]);
        //var_dump($dc2array);

        if($form->isSubmitted()&& $form->isValid())
        {
            $path=$this->getParameter('kernel.project_dir').'/public/back/img';
            $dermatologues=$form->getData();
            $file=$dermatologues->getImage();
            $fileName=md5(uniqid()).'.'.$file->guessExtension();
            try {
                $file->move($path,$fileName);
            }catch(FileException $e){

            }

            $dermatologues->setImage($fileName);
            $em->persist($dermatologues);
            $em->flush();
            $this->supprimer($id);


            return $this->redirectToRoute('dermatologues');
        }

        return $this->render ('dermatologue/Ajoutderm.html.twig',[
            'form'=>$form->createView(),

        ]) ;


    }
}

templates/dermatologue/Ajoutderm.html.twig
{% extends 'back_base.html.twig' %}
{% block title %}ajouter Dermatologues {% endblock %}

{% block body %}
    {{ form_start (form,{'attr': {'novalidate': 'novalidate'}}) }}
<h1>Ajouter Dermatologue </h1>
{#{{ form_errors(form.id) }}
    {{ form_label(form.id,"id") }}
    {{ form_widget(form.id) }}
#}

    {{ form_label(form.diplome,"Diplome") }}
    {{ form_widget(form.diplome) }}


    {{ form_label(form.formation,"formation") }}
    {{ form_widget(form.formation) }}


    {{ form_label(form.langue,"Langue") }}
    {{ form_widget(form.langue) }}
    {{ form_errors(form.langue) }}


    {{ form_label(form.horaire,"horaire") }}
    {{ form_widget(form.horaire) }}


    {{ form_label(form.modereglement,"mode de reglement") }}
    {{ form_widget(form.modereglement) }}


    {{ form_label(form.assurancemaladie,"assurrancemaladie") }}
    {{ form_widget(form.assurancemaladie) }}



    {{ form_label(form.image) }}
    {{ form_widget(form.image) }}


    {{ form_label(form.categorie) }}
    {{ form_widget(form.categorie) }}

    {{ form_end(form) }}
{% endblock %}

templates/dermatologue/ModifDerm.html.twig
{% extends 'back_base.html.twig' %}
{% block title %} modifier Dermatologues {% endblock %}
{% block body %}

{#  {{ form(f) }} #}
    {{ form_start (f,{'attr': {'novalidate': 'novalidate'}}) }}
    <h1>Modifier Dermatologue </h1>
    {#{{ form_errors(form.cin) }}
    {{ form_label(f.cin,"Cin") }}
    {{ form_widget(f.cin) }}
    #}

    {{ form_label(f.diplome,"Diplome") }}
    {{ form_widget(f.diplome) }}


    {{ form_label(f.formation,"formation") }}
    {{ form_widget(f.formation) }}


    {{ form_label(f.langue,"Langue") }}
    {{ form_widget(f.langue) }}


    {{ form_label(f.horaire,"horaire") }}
    {{ form_widget(f.horaire) }}


    {{ form_label(f.modereglement,"mode de reglement") }}
    {{ form_widget(f.modereglement) }}


    {{ form_label(f.assurancemaladie,"assurrancemaladie") }}
    {{ form_widget(f.assurancemaladie) }}



    {{ form_label(f.image) }}
    {{ form_widget(f.image) }}


    {{ form_label(f.categorie) }}
    {{ form_widget(f.categorie) }}

    {{ form_end(f) }}


{% endblock %}

templates/dermatologue/affichederm.html.twig

{% extends 'back_base.html.twig' %}
{% block title %} afficher dermatologue {% endblock %}

{% block body %}
    <div class="container-fluid">
    <div class="card shadow mb-4">
    <div class="card-header py-3">
    <h1>Liste des Dermatologues </h1>
    <div class="card-body">
    <div class="table-responsive">
    <table border="2" class="table table-bordered"  width="100%" cellspaidg="0">
        <thead>
        <th>id</th>
        <th>Diplome</th>
        <th>Formation</th>
        <th>Langue</th>
        <th>Horaire</th>
        <th>Mode De reglement</th>
        <th>Assurance Maladie</th>
        <th>Image</th>
        <th>Email</th>

       {# <th> Update </th>
          <th>Delete</th>
       #}

        </thead>
        {% for d in dermatologues %}
            <tbody>

            <td>{{ d.id }}</td>
            <td>{{ d.diplome }}</td>
            <td>{{ d.formation }}</td>
            <td>{{ d.langue }}</td>
            <td>{{ d.horaire }}</td>
            <td>{{ d.modereglement}}</td>
            <td>{{ d.assurancemaladie }}</td>

            <td><img src="{{ asset('/back/img/'~d.image) }}" alt="" style="width: 400px ; height:auto ">
            </td>
            <td>{{ d.email }}</td>
            <td> <a href="  {{path('updatederm',{'id':d.id}) }}" class="btn btn-warning btn-circle"><i class="fas fa-exclamation-triangle"></i></a>
                 <a href="  {{path('derm',{'id':d.id}) }}" class="btn btn-danger btn-circle" ><i class="fas fa-trash"></i></a>

            </td>
            </tbody>
        {% endfor %}
    </table>

    </div>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

templates/dermatologue/afficher1dermatologuefront.html.twig
{% extends 'front_base.html.twig' %}
{% block title %} afficher dermatologue front  {% endblock %}
{% block body %}

    <div id="tab_1" class="tab_container active">
        <div class="row">
            <div class="col-lg-5 desc_col">
                <div class="tab_title">
                    <h4>Dermatologue</h4>
                </div>
                <div class="product_image">
                    <img src="{{ asset('/back/img/'~ dermatologues.image) }}" alt="">
                </div>


            </div>

            <div class="col-lg-5">
                <div class="product_details">
                    <div class="product_details_title">
                        <h2>{{ dermatologues.id }}</h2>
                        <p>Ce dermatologue est bien nommé </p>
                    </div>

                    <div class="original_price">{{ dermatologues.diplome }}</div>
                    <div class="original_price">{{ dermatologues.formation}}</div>
                    <div class="original_price">{{ dermatologues.horaire}}</div>
                    <div class="original_price">{{ dermatologues.modereglement}}</div>
                </div>
            </div>
        </div>

    </div>




{% endblock %}

templates/dermatologue/afficherdermatologuefront.html.twig
{% extends 'front_base.html.twig' %}
{% block title %} afficher dermatologues front  {% endblock %}
{% block body %}

<div class="container product_section_container">

    <div class="col product_section clearfix">

        <!-- Breadcrumbs -->

        <div class="breadcrumbs d-flex flex-row align-items-center">
            <ul>
                <li><a href="index.html">Home</a></li>
                <li class="active"><a href="index.html"><i class="fa fa-angle-right" aria-hidden="true"></i>Men's</a></li>
            </ul>
        </div>

        <!-- Sidebar -->

        <div class="sidebar">
            <div class="sidebar_section">
                <div class="sidebar_title">
                    <h5> catégorie des Dermatologue </h5>
                </div>
                <ul class="sidebar_categories">
                    {% for dc in categories %}
                    <a href="{{ path('dermfront',{'ref':dc.ref}) }}">

                        <ul>
                            {{ dc.localisation }}
                        </ul>

                    </a>
                </ul>
                {% endfor %}

            </div>
            <!--
        <li><a href="#">categ1</a></li>
        <li class="active"><a href="#"><span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>categ2</a></li>
        <li><a href="#">cat3</a></li>
        <li><a href="#">cat4</a></li>
        <li><a href="#">cat5</a></li>
        <li><a href="#">cat6</a></li>
--->


            <!-- Price Range Filtering -->

            <div class="sidebar_section">
                <div class="sidebar_title">
                    <h5>Filter by Price</h5>
                </div>
                <p>
                    <input type="text" id="amount" readonly style="border:0; color:#f6931f; font-weight:bold;">
                </p>
                <div id="slider-range"></div>
                <div class="filter_button"><span>filter</span></div>
            </div>

            <!-- Sizes -->
            <div class="sidebar_section">
                <div class="sidebar_title">
                    <h5>Sizes</h5>
                </div>
                <ul class="checkboxes">
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>S</span></li>
                    <li class="active"><i class="fa fa-square" aria-hidden="true"></i><span>M</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>L</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>XL</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>XXL</span></li>
                </ul>
            </div>

            <!-- Color -->
            <div class="sidebar_section">
                <div class="sidebar_title">
                    <h5>Color</h5>
                </div>
                <ul class="checkboxes">
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Black</span></li>
                    <li class="active"><i class="fa fa-square" aria-hidden="true"></i><span>Pink</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>White</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Blue</span></li>
                    <li><i class="fa fa-square-o" aria-hidden="true"></i><span>Orange</span></li>
                </ul>
                <div class="show_more">
                    <span><span>+</span>Show More</span>
                </div>
            </div>

        </div>

        <!-- Main Content -->

        <div class="main_content">

            <!-- Products -->

            <div class="products_iso">
                <div class="row">


                    <!-- Product Sorting -->


                    <!-- Product Grid -->


                    <div class="product-grid">

                        <!-- Product 1 -->




                            {% for d in dermatologues %}
                                    {% if ref == d.categorie.ref %}
                                <div class="product-item men">
                                    <div class="product discount product_filter">
                                        <div class="product_image">
                                            <img src="{{ asset('/back/img/'~ d.image) }}" alt="">
                                        </div>
                                        <div class="favorite favorite_left"></div>
                                        <div class="product_bubble product_bubble_right product_bubble_red d-flex flex-column align-items-center"><span>-$20</span></div>
                                        <div class="product_info">
                                            <h6 class="product_name">{{ d.id }}</h6>
                                            <div class="product_price">{{ d.diplome }}></div>
                                        </div>
                                    </div>
                                    <div class="red_button add_to_cart_button"><a href="{{ path('dermfront1',{'id':d.id}) }}">consulter</a></div>
                                </div>
                                {% endif %}
                            {% endfor %}

                    </div>





                    {% endblock %}


templates/dermatologue/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DermatologueController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/wamp64/www/Dermabeauty/src/Controller/DermatologueController.php'|file_link(0) }}">src/Controller/DermatologueController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/wamp64/www/Dermabeauty/templates/dermatologue/index.html.twig'|file_link(0) }}">templates/dermatologue/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}